#!/bin/bash

cd /usr/share/rpi-smart-still

while [ true ]; do
  ScriptStart=$(date +%s)
  ./write-outputs.php
  ScriptEnd=$(date +%s)
  Runtime=$(($ScriptEnd - $ScriptStart))
  echo "Script Runtime: $Runtime seconds"
  if [ $Runtime -lt 5 ]; then
    Delay=$((5 - $Runtime))
    echo "Sleeping $Delay seconds"
    sleep $Delay
  fi
  ./play-prompts.php
done
