#!/bin/bash

cd /usr/share/rpi-smart-still

while [ true ]; do
  ScriptStart=$(date +%s)
  ./play-prompts.php
  ScriptEnd=$(date +%s)
  Runtime=$(($ScriptEnd - $ScriptStart))
  echo "Script Runtime: $Runtime seconds"
  if [ $Runtime -lt 2 ]; then
    Delay=$((2 - $Runtime))
    echo "Sleeping $Delay seconds"
    sleep $Delay
  fi
done
