#!/bin/bash

cd /usr/share/rpi-smart-still

sleep 0.9

while [ true ]; do
  ScriptStart=$(date +%s)
  if [ -f /usr/share/rpi-smart-still/ds18b20 ]; then
    /usr/share/rpi-smart-still/ds18b20 > /tmp/rss_ds18b20
  fi
  ./read-inputs.php
  ScriptEnd=$(date +%s)
  Runtime=$(($ScriptEnd - $ScriptStart))
  echo "Script Runtime: $Runtime seconds"
  if [ $Runtime -lt 10 ]; then
    Delay=$((10 - $Runtime))
    echo "Sleeping $Delay seconds"
    sleep $Delay
  fi
done
